packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/node@26.1.2'
  - '@supabase/auth-js@2.110.9'
  - '@supabase/functions-js@2.110.9'
  - '@supabase/postgrest-js@2.110.9'
  - '@supabase/realtime-js@2.110.9'
  - '@supabase/storage-js@2.110.9'
  - '@supabase/supabase-js@2.110.9'
